title: Apple: Road to Mobile
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: Writing a book about Apple is almost as foolish as reading one.

url: https://tangero.github.io/apple-mobile

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
